import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Routes, Route, Navigate } from 'react-router';
import '../../App.css';
import "leaflet/dist/leaflet.css";
import 'leaflet-geosearch/dist/geosearch.css';
import Login from '../../components/User/Login/Logn';
import Signup from '../../components/User/Signup/Signup';
import Otp from '../../components/User/OTP/Otp';
import Home from '../../components/User/Home/Home';
import ForgetPassword from '../../components/User/Forgetpassword/Forgetpassword';
import ForgetPasswordOTp from '../../components/User/Forgetpassword/ForgetPasswordOTp';
import ChangePassword from '../../components/User/Forgetpassword/ChangePassword';
import { Toaster } from 'react-hot-toast';
import UserLayout from '../../components/User/Profile/Userlayout';
import ProfilePage from '../../components/User/Profile/ProfilePage';
import TechnicianList from '../../components/User/AvailableTech.tsx/Availabletech';
import TechnicianProfile from '../../components/User/Techprofile/Profile';
import AddressPage from '../../components/User/Profile/Address';
import PaymentPage from '../../components/User/Payment/ProceedPayment';
import ThankYouPage from '../../components/User/ThankYou/ThankYou';
import Services from '../../components/User/Profile/Service';
import ViewBookingsProfile from '../../components/User/Profile/ViewBookings';
import ChangePasswords from '../../components/User/Profile/Password';
import ThankYouPageService from '../../components/User/Thankyouservice/ThankYouService';
import WalletPage from '../../components/User/Profile/Wallet';
const UserRouter = () => {
    return (_jsxs(_Fragment, { children: [_jsx(Toaster, {}), _jsxs(Routes, { children: [_jsx(Route, { path: '/', element: _jsx(Home, {}) }), _jsx(Route, { path: '/login', element: _jsx(Login, {}) }), _jsx(Route, { path: '/signup', element: _jsx(Signup, {}) }), _jsx(Route, { path: '/otp', element: _jsx(Otp, {}) }), _jsx(Route, { path: '/forgetpassword', element: _jsx(ForgetPassword, {}) }), _jsx(Route, { path: '/forgetpassotp', element: _jsx(ForgetPasswordOTp, {}) }), _jsx(Route, { path: '/changepassword', element: _jsx(ChangePassword, {}) }), _jsx(Route, { path: '/available-technicians', element: _jsx(TechnicianList, {}) }), _jsx(Route, { path: '/viewprofile', element: _jsx(TechnicianProfile, {}) }), _jsx(Route, { path: '/proceedpayment', element: _jsx(PaymentPage, {}) }), _jsx(Route, { path: '/thankyou', element: _jsx(ThankYouPage, {}) }), _jsx(Route, { path: '/thankyouservice', element: _jsx(ThankYouPageService, {}) }), _jsx(Route, { path: '/viewbookingddetails', element: _jsx(ViewBookingsProfile, {}) }), _jsxs(Route, { path: '/myaccount', element: _jsx(UserLayout, {}), children: [_jsx(Route, { index: true, element: _jsx(Navigate, { to: "profile", replace: true }) }), _jsx(Route, { path: "profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: 'addressmanagment', element: _jsx(AddressPage, {}) }), _jsx(Route, { path: 'services', element: _jsx(Services, {}) }), _jsx(Route, { path: 'passwordchange', element: _jsx(ChangePasswords, {}) }), _jsx(Route, { path: 'wallet', element: _jsx(WalletPage, {}) })] })] })] }));
};
export default UserRouter;
