import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router";
const ThankYouPage = () => {
    const navigate = useNavigate();
    const handleClick = () => {
        navigate('/myaccount/services');
    };
    return (_jsxs("div", { className: "min-h-screen flex flex-col", children: [_jsxs("header", { className: "bg-[#0B1C42] text-white flex items-center justify-between px-6 py-4", children: [_jsx("div", { className: "text-xl font-bold", children: "HomePro" }), _jsxs("nav", { className: "space-x-6", children: [_jsx("a", { href: "#", className: "hover:underline", children: "Home" }), _jsx("a", { href: "#", className: "hover:underline", children: "Services" }), _jsx("a", { href: "#", className: "hover:underline", children: "Contact" })] }), _jsx("div", { className: "font-medium", children: "My Profile" })] }), _jsx("main", { className: "flex-grow flex items-center justify-center bg-gray-50 px-4 py-20", children: _jsxs("div", { className: "bg-white rounded-xl shadow-lg text-center p-8 max-w-md w-full", children: [_jsx("div", { className: "bg-[#0B1C42] text-white rounded-t-xl py-4 text-lg font-semibold", children: "Successful Order" }), _jsxs("div", { className: "py-10", children: [_jsx("img", { src: "/success-box-icon.svg" // Replace with actual icon path
                                    , alt: "Success Icon", className: "mx-auto mb-6 w-20 h-20" }), _jsx("h2", { className: "text-xl font-semibold mb-2", children: "Thank you for the booking!!" }), _jsx("p", { className: "text-gray-600 mb-6", children: "Your order has been successfully placed and is now being processed." }), _jsx("button", { onClick: handleClick, className: "bg-blue-500 hover:bg-blue-600 text-white px-6 py-2 rounded-full", children: "View Service" })] })] }) }), _jsxs("footer", { className: "bg-[#0B1C42] text-white text-sm px-6 py-8 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6", children: [_jsxs("div", { children: [_jsx("div", { className: "font-bold text-lg mb-2", children: "HomePro" }), _jsx("p", { children: "Your Home, Our Priority" })] }), _jsxs("div", { children: [_jsx("div", { className: "font-semibold mb-1", children: "HELP" }), _jsxs("ul", { className: "space-y-1", children: [_jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "Contact Us" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "FAQ" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "Privacy Policy" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "Terms of Service" }) })] })] }), _jsxs("div", { children: [_jsx("div", { className: "font-semibold mb-1", children: "MORE" }), _jsxs("ul", { className: "space-y-1", children: [_jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "About Us" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "Careers" }) }), _jsx("li", { children: _jsx("a", { href: "#", className: "hover:underline", children: "Blog" }) })] })] })] })] }));
};
export default ThankYouPage;
